blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('posts/<slug:slug>', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/share/', views.post_share, name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('category/<slug:category_slug>/', views.post_by_category, name='post_by_category'),
    path('resume/', views.resume_page, name='resume_page'),
    path('contacts/', views.contacts_page, name='contacts_page'),
]

learn_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('published', 'Опубликован')
    )
    title = models.CharField(max_length=150, verbose_name='Название')
    slug = models.SlugField(max_length=160, unique=True, verbose_name='Слаг')
    category = models.ForeignKey('Category',
                                 on_delete=models.SET_NULL,
                                 related_name='category',
                                 null=True,
                                 verbose_name='Категория')
    author = models.ForeignKey(User,
                               related_name='blog_posts',
                               on_delete=models.CASCADE,
                               verbose_name='Автор')
    image = models.ImageField(upload_to='images/posts/',
                              default='images/default.jpg',
                              verbose_name='Постер')
    content = models.TextField(verbose_name='Контент')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft',
                              verbose_name='Статус')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    category_slug = models.SlugField(unique=True, verbose_name='Слаг')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_by_category', kwargs={'category_slug': self.category_slug})


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name='Пост')
    name = models.CharField(max_length=80, verbose_name='Имя')
    email = models.EmailField(verbose_name='E-mail')
    content = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлён')
    active = models.BooleanField(default=True, verbose_name='Активный')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        return f'Комментарий от {self.name} - {self.post}'


class PostPics(models.Model):
    alt = models.CharField(max_length=255, verbose_name='Название')
    image = models.ImageField(upload_to='images/posts/pics', verbose_name='Изображение')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')

    def __str__(self):
        return f"{self.alt} - {self.post.title}"

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')


class SearchForm(forms.Form):
    query = forms.CharField(max_length=255)

blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from .models import Post, Category
from .forms import EmailPostForm, CommentForm
from taggit.models import Tag
from django.db.models import Count, Q


def post_list(request, tag_slug=None):
    object_list = Post.published.annotate(num_comments=Count('comments')).all()
    paginator = Paginator(object_list, 5)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'page': page,
               'posts': posts, }
    return render(request, 'blog/post/list.html', context)


def post_search(request):
    if request.method == "GET":
        query = request.GET.get('search')
        submit_button = request.GET.get('submit')

        if query is not None:
            lookups = Q(title__icontains=query) | Q(content__icontains=query)
            results = Post.objects.filter(lookups).distinct().order_by('-publish')
            context = {'posts': results,
                       'submit_button': submit_button}
            return render(request, 'blog/post/list.html', context)
        else:
            return render(request, 'blog/post/list.html')
    else:
        return render(request, 'blog/post/list.html')


def post_detail(request, slug):
    post = get_object_or_404(Post.objects.annotate(num_comments=Count('comments')), slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {'post': post,
               'comments': comments,
               'new_comment': new_comment,
               'comment_form': comment_form,
               'similar_posts': similar_posts}
    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} советует вам прочитать {post.title}"
            message = f"Прочитай {post.title} тут - {post_url}\n\n Комментарий от {cd['name']}: {cd['comments']}"
            send_mail(subject, message, 'timur3214t@gmail.com', [cd['to']], fail_silently=False)
            sent = True
    else:
        form = EmailPostForm()
    context = {'post': post,
               'form': form,
               'sent': sent}
    return render(request, 'blog/post/share.html', context)


def post_by_category(request, category_slug):
    # Сортировать статьи по категориям
    objects_list = Post.objects.filter(category__category_slug=category_slug).order_by('publish')
    if not objects_list:
        raise Http404("Категория не найдена")
    category = Category.objects.get(category_slug=category_slug)
    paginator = Paginator(objects_list, 5)
    page = request.GET.get('page')
    try:
        objects_list = paginator.page(page)
    except PageNotAnInteger:
        objects_list = paginator.page(1)
    except EmptyPage:
        objects_list = paginator.page(paginator.num_pages)
    context = {
        'category': category,
        'posts': objects_list,
        'page': page,
    }
    return render(request, 'blog/post/list.html', context)


def resume_page(request):
    resume_url = request.path
    return render(request, 'blog/resume/resume.html', {'resume_url': resume_url})


def contacts_page(request):
    contacts_url = request.path
    return render(request, 'blog/contacts/contacts.html', {'contacts_url': contacts_url})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
{% url 'blog:post_list' as index %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>{% block title %}{% endblock %} - Tim Hale Blog</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="{% static 'fancybox/jquery.fancybox.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
<style>
    body {
        background:url({% static 'images/hbg_img.jpg' %}) no-repeat center 112px;
    }
    .content p.date {
        background:#f00 {% static 'images/date_bg.gif' %} no-repeat left top;
    }
</style>
<script type="text/javascript" src="{% static 'js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'js/arial.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cuf_run.js' %}"></script>
</head>
<body>
<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><a href="{% url 'blog:post_list' %}"><img src="{% static 'images/logo.jpg' %}" width="48" height="50" alt="" /></a><a href="{% url 'blog:post_list' %}">Tim<span>Hale</span> <small>@timhale2104</small></a></h1>
      </div>
      <div class="menu_nav">
        <ul>
          <li {% ifequal request.path index %}class="active"{% endifequal %}><a href="{% url 'blog:post_list' %}">Главная</a></li>
          <li {% ifequal request.path resume_url %}class="active"{% endifequal %}><a href="{% url 'blog:resume_page' %}">Резюме</a></li>
          <li {% ifequal request.path contacts_url %}class="active"{% endifequal %}><a href="{% url 'blog:contacts_page' %}">Контакты</a></li>
        </ul>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="hbg">&nbsp;</div>
{% block content %}

{% endblock %}
<div class="sidebar">
        <div class="searchform">
          <form id="formsearch" name="formsearch" method="GET" value="{{ request.GET.q }}" action="{% url 'blog:post_search' %}">
            <span>
            <input name="search" class="editbox_search" id="editbox_search" style="border: 1px solid black" maxlength="80" placeholder="Поиск" value="{{ request.GET.search }}" type="text" required>
            </span>
              <button name="button_search" type="submit" style="border: 1px solid black; padding: 12px 10px; margin-top: 0.45em;" value="search">Искать</button>
          </form>
        </div>
        <div class="gadget">
          <h2 class="star">Категории</h2>
          <div class="clr"></div>
          <ul class="sb_menu">
              {% for category in categories %}
                  <li><a href="#">{{ category.name }}</a></li>
              {% endfor %}
          </ul>
        </div>
        <div class="gadget">
          <h2 class="star"><span>Последние посты</span></h2>
          <div class="clr"></div>
          {% latest_posts %}
        </div>
        <div class="gadget">
          <h2 class="star"><span>Комментируемые посты</span></h2>
          <div class="clr"></div>
          {% commented_posts %}
        </div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="footer">
    <div class="footer_resize">
      <p class="lf">Copyright &copy; <a href="{% url 'blog:post_list' %}">Tim Hale Blog</a>. All Rights Reserved</p>
      <p class="rf">Design by <a target="_blank" href="http://www.iwebsitetemplate.com/">IWebsiteTemplate</a></p>
      <div class="clr"></div>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'fancybox/jquery-1.3.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fancybox/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'fancybox/jquery.fancybox-1.2.1.pack.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $("a.first").fancybox();
        $("a.two").fancybox();
        $("a.video").fancybox({"frameWidth":520,"frameHeight":400});
        $("a.content").fancybox({"frameWidth":600,"frameHeight":300});
    });
</script>
</body>
</html>

blog/templates/blog/pagination.html
<p class="pages">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}" style="text-decoration: none">Назад</a>
    {% endif %}
    <small>Страница {{ page.number }} из {{ page.paginator.num_pages }}</small>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}" style="text-decoration: none">Вперёд</a>
    {% endif %}
</p>