blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('posts/<slug:slug>', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/share/', views.post_share, name='post_share'),
    path('search/', views.post_search, name='post_search'),
    path('category/<slug:category_slug>/', views.post_by_category, name='post_by_category'),
    path('resume/', views.resume_page, name='resume_page'),
    path('contacts/', views.contacts_page, name='contacts_page'),
]

learn_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('published', 'Опубликован')
    )
    title = models.CharField(max_length=150, verbose_name='Название')
    slug = models.SlugField(max_length=160, unique=True, verbose_name='Слаг')
    category = models.ForeignKey('Category',
                                 on_delete=models.SET_NULL,
                                 related_name='category',
                                 null=True,
                                 verbose_name='Категория')
    author = models.ForeignKey(User,
                               related_name='blog_posts',
                               on_delete=models.CASCADE,
                               verbose_name='Автор')
    image = models.ImageField(upload_to='images/posts/',
                              default='images/default.jpg',
                              verbose_name='Постер')
    content = models.TextField(verbose_name='Контент')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft',
                              verbose_name='Статус')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    category_slug = models.SlugField(unique=True, verbose_name='Слаг')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_by_category', kwargs={'category_slug': self.category_slug})


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name='Пост')
    name = models.CharField(max_length=80, verbose_name='Имя')
    email = models.EmailField(verbose_name='E-mail')
    content = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлён')
    active = models.BooleanField(default=True, verbose_name='Активный')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        return f'Комментарий от {self.name} - {self.post}'


class PostPics(models.Model):
    alt = models.CharField(max_length=255, verbose_name='Название')
    image = models.ImageField(upload_to='images/posts/pics', verbose_name='Изображение')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')

    def __str__(self):
        return f"{self.alt} - {self.post.title}"

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')


class SearchForm(forms.Form):
    query = forms.CharField(max_length=255)

blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from .models import Post, Category
from .forms import EmailPostForm, CommentForm
from taggit.models import Tag
from django.db.models import Count, Q


def post_list(request, tag_slug=None):
    object_list = Post.published.annotate(num_comments=Count('comments')).all()
    paginator = Paginator(object_list, 5)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'page': page,
               'posts': posts, }
    return render(request, 'blog/post/list.html', context)


def post_search(request):
    if request.method == "GET":
        query = request.GET.get('search')
        submit_button = request.GET.get('submit')

        if query is not None:
            lookups = Q(title__icontains=query) | Q(content__icontains=query)
            results = Post.objects.filter(lookups).distinct().order_by('-publish')
            context = {'posts': results,
                       'submit_button': submit_button}
            return render(request, 'blog/post/list.html', context)
        else:
            return render(request, 'blog/post/list.html')
    else:
        return render(request, 'blog/post/list.html')


def post_detail(request, slug):
    post = get_object_or_404(Post.objects.annotate(num_comments=Count('comments')), slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {'post': post,
               'comments': comments,
               'new_comment': new_comment,
               'comment_form': comment_form,
               'similar_posts': similar_posts}
    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} советует вам прочитать {post.title}"
            message = f"Прочитай {post.title} тут - {post_url}\n\n Комментарий от {cd['name']}: {cd['comments']}"
            send_mail(subject, message, 'timur3214t@gmail.com', [cd['to']], fail_silently=False)
            sent = True
    else:
        form = EmailPostForm()
    context = {'post': post,
               'form': form,
               'sent': sent}
    return render(request, 'blog/post/share.html', context)


def post_by_category(request, category_slug):
    # Сортировать статьи по категориям
    objects_list = Post.objects.filter(category__category_slug=category_slug).order_by('publish')
    if not objects_list:
        raise Http404("Категория не найдена")
    category = Category.objects.get(category_slug=category_slug)
    paginator = Paginator(objects_list, 5)
    page = request.GET.get('page')
    try:
        objects_list = paginator.page(page)
    except PageNotAnInteger:
        objects_list = paginator.page(1)
    except EmptyPage:
        objects_list = paginator.page(paginator.num_pages)
    context = {
        'category': category,
        'posts': objects_list,
        'page': page,
    }
    return render(request, 'blog/post/list.html', context)


def resume_page(request):
    resume_url = request.path
    return render(request, 'blog/resume/resume.html', {'resume_url': resume_url})


def contacts_page(request):
    contacts_url = request.path
    return render(request, 'blog/contacts/contacts.html', {'contacts_url': contacts_url})

blog/templates/blog/post/category.html
{% extends 'blog/base.html' %}
{% block title %}
    Категория: {{ category.name }}
{% endblock %}
{% block content %}

{% endblock %}
{% if posts %}
        {% for post in posts %}
            <h2>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <p class="date">
                Опубликован {{ post.publish }} пользователем {{ post.author }}
            </p>
            {{ post.content|truncatewords:30|striptags|safe|linebreaks }}
            <p class="tags">
                Категория: <a href="{% url 'blog:post_by_category' post.category.category_slug %}">{{ category.name }}</a>
            </p>
            <p class="tags">
                Теги:
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <hr>
        {% endfor %}
            {% include 'blog/pagination.html' with page=posts %}
    {% endif %}

blog/templates/blog/post/commented_posts.html
<ul class="ex_menu">
    {% for post in commented_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="content">
    <div class="content_resize">
      <div class="mainbar">
        <div class="article">
          <h2>{{ post.title }}</h2>
          <div class="clr"></div>
          <p>Автор <a href="https://t.me/timhale2104" target="_blank">{{ post.author }}</a> <span>&nbsp;&bull;&nbsp;</span> Категория <a href="{% url 'blog:post_by_category' post.category.category_slug %}">{{ post.category.name }}</a></p>
           <p>
               <img src="{{ post.image.url }}" width="590" height="350">
           </p>
          <p>{{ post.content|safe|linebreaks }}</p>
            <p>
            <h3>Изображения поста</h3>
            <div align="center" style="display: flex; flex-wrap: wrap; justify-content: space-around;">
                {% for image in post.postpics_set.all %}
                    <a href="{{ image.image.url }}" class="two" rel="group" style="margin-top: 1em;"><img src="{{ image.image.url }}" width="250" height="200"></a>
                {% endfor %}
            </div>
            </p>
            <br>
          <p><a href="{% url 'blog:post_share' post.id %}">Поделиться по Email</a></p>
            <p>
                <h2>Похожие посты</h2>
                {% for post in similar_posts %}
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> |
                    {% empty %}
                    Похожих постов пока что нет :(
                {% endfor %}
            </p>
          <p><strong>Комментов ({{ post.num_comments }})</strong> <span>&nbsp;&bull;&nbsp;</span>Дата публикации: {{ post.publish }} <span>&nbsp;&bull;&nbsp;</span></p>
        </div>
        <div class="article">
          <h2>Комментарии</h2>
          <div class="clr"></div>
            {% for comment in comments %}
                 <div class="comment"> <a href="#"><img src="{% static 'images/userpic.gif' %}" width="40" height="40" alt="" class="userpic" /></a>
                    <p><b>{{ comment.name }}</b><br />
                      {{ comment.created }}</p>
                    <p>{{ comment.content|linebreaks }}</p>
                 </div>
            {% empty %}
                <p>Комментариев пока что нет <i>:(</i></p>
            {% endfor %}
        </div>
        <div class="article">
          <h2>Комментировать</h2>
          <div class="clr"></div>
          <form method="post" id="leavereply">
          {% csrf_token %}
            <ol>
              <li>
                <label for="name">Имя (обязательно)</label>
                <input id="name" name="name" class="text" />
              </li>
              <li>
                <label for="email">Email (Обязательно)</label>
                <input id="email" name="email" class="text" />
              </li>
              <li>
                <label for="content">Комментарий</label>
                <textarea id="content" name="content" rows="8" cols="50"></textarea>
              </li>
              <li>
                  <button type="submit" style="border: 1px solid gray; padding: 12px 10px; margin-top: 0.45em;" value="commented">Отправить</button>
                <div class="clr"></div>
              </li>
            </ol>
          </form>
        </div>
      </div>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul class="ex_menu">
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}
{% block title %}
    {% if request.GET.search %}
        Поиск: {{ request.GET.search }}
    {% elif category%}
        {{ category.name }}
    {% else %}
        Главная
    {% endif %}
{% endblock %}
{% block content %}
    <div class="content">
    <div class="content_resize">
      <div class="mainbar">
      {% if posts %}
          {% for post in posts %}
            <div class="article">
              <h2><span><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></span></h2>
                <p>Posted by <b>{{ post.author }}</b> &nbsp;|&nbsp; Категория <a href="{% url 'blog:post_by_category' post.category.category_slug %}">{{ post.category.name }}</a><a href="#" class="com">Комментариев {{ post.num_comments }}</a></p>
              <img src="{{ post.image.url }}" width="605" height="250" alt="" />
              <p>{{ post.content|truncatewords:30|striptags|safe|linebreaks }}</p>
              <p class="spec"><a href="{{ post.get_absolute_url }}" class="rm">Читать &raquo;</a></p>
            </div>
          {% empty %}
              Постов пока что нет :(<br>Но они скоро будут :D
          {% endfor %}
        {% include 'blog/pagination.html' with page=posts %}
      {% else %}
          <br>
          <br>
          <br>
          <br>
          <h2>По запросу "{{ request.GET.search }}" ничего не найдено :(</h2>
      {% endif %}
      </div>
{% endblock %}

{#{% if request.GET.search %}#}
{#        Поиск по запросу: {{ request.GET.search }}#}
{#    {% endif %}#}
{#    {% if posts %}#}
{#        {% for post in posts %}#}
{#            <h2>#}
{#                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>#}
{#            </h2>#}
{#            <p class="date">#}
{#                Опубликован {{ post.publish }} пользователем {{ post.author }}#}
{#            </p>#}
{#            <p><img src="{{ post.image.url }}" width="800" height="400"></p>#}
{#            {{ post.content|truncatewords:30|striptags|safe|linebreaks }}#}
{#            <p class="tags">#}
{#                Категория: <a href="{% url 'blog:post_by_category' post.category.category_slug %}">{{ post.category.name }}</a>#}
{#            </p>#}
{#            <p class="tags">#}
{#                Теги:#}
{#                {% for tag in post.tags.all %}#}
{#                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">#}
{#                        {{ tag.name }}#}
{#                    </a>#}
{#                    {% if not forloop.last %}, {% endif %}#}
{#                {% endfor %}#}
{#            </p>#}
{#            <hr>#}
{#        {% empty %}#}
{#            <h1>Постов пока что нет, но они скоро будут :)</h1>#}
{#        {% endfor %}#}
{#            {% include 'blog/pagination.html' with page=posts %}#}
{#    {% else %}#}
{#        <h2>По запросу "{{ request.GET.search }}" ничего не найдено :(</h2>#}
{#    {% endif %}#}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Поделиться постом{% endblock %}
{% block content %}
<div class="content">
<div class="content_resize">
  <div class="mainbar">
  <div class="article">
          <h2>Поделиться "{{ post.title }}" через e-mail</h2>
          <div class="clr"></div>
          {% if sent %}
              <br>
              <br>
              <br>
              <br>
                <h1>E-mail успешно отправлен</h1>
                <p>"{{ post.title }}" успешно отправлен {{ form.cleaned_data.to }}</p>
              <br>
              <br>
              <br>
              <br>
              </div>
              </div>
          {% else %}
          <form method="POST">
          {% csrf_token %}
            <ol>
              <li>
                <label for="{{ form.name.id_for_label }}">Имя (обязательно)</label>
                {{ form.name }}
              </li>
              <li>
                <label for="{{ form.email.id_for_label }}">Email отправителя (Обязательно)</label>
                {{ form.email }}
              </li>
                <li>
                <label for="{{ form.to.id_for_label }}">Email получателя (Обязательно)</label>
                {{ form.to }}
              </li>
              <li>
                <label for="{{ form.comments.id_for_label }}">Комментарий</label>
                {{ form.comments }}
              </li>
              <li>
                  <input type="submit" style="border: 1px solid gray; padding: 12px 10px; margin-top: 0.45em;" value="Поделиться">
                <div class="clr"></div>
              </li>
            </ol>
          </form>
        </div>
      </div>
    {% endif %}
{% endblock %}